USE master;
GO

--CREACION DE LA BASE DE DATOS
CREATE DATABASE Biblioteca
ON PRIMARY
(NAME = Biblio_dat,
 FILENAME = 'E:\SQL Data\Biblio_dat.mdf',
 SIZE = 1GB,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 64MB)
LOG ON
(NAME = Biblio_log,
 FILENAME = 'E:\SQL Data\Biblio_log.ldf',
 SIZE = 256MB,
 MAXSIZE = UNLIMITED,
 FILEGROWTH = 64MB);
GO

USE Biblioteca;
GO

--CREACION DE TABLAS
CREATE TABLE Juvenil
(NumeroSocio INT NOT NULL,
 NumMiembroAdulto INT NOT NULL,
 FechaNac DATE NOT NULL);
GO

--VALIDACION DE LA CREACION DE LA TABLA
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Juvenil';

--ELIMINAR TABLA
DROP TABLE Juvenil;
GO

--VALIDACION DE LA CREACION DE LA TABLA
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_NAME = 'Juvenil';

--CREACION DE LA TABLA MIEMBROS
CREATE TABLE Miembros
(NroMiembro INT IDENTITY(1,1) NOT NULL, 
 Apellidos VARCHAR(20) NOT NULL,
 Nombres VARCHAR(20) NOT NULL,
 Iniciales CHAR(3) NULL);
GO

--DROP TABLE Miembros;

SP_HELP Miembros;

--CREATE - CREAR OBJETOS (BASE DE DATOS, TABLAS)
--DROP - ELIMINAR OBJETOS (BASE DE DATOS, TABLAS)
--ALTER - MODIFICAR OBJETOS

--AÑADIR UNA COLUMNA A LA TABLA Miembros
ALTER TABLE Miembros
ADD Edad TINYINT NULL;
GO

SP_HELP Miembros;

--ELIMINAR UNA COLUMNA DE LA TABLA
ALTER TABLE Miembros
DROP COLUMN Edad;
GO